#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -R 0
rm -R processor*
cleanTimeDirectories;
cleanCase;
\rm -R constant/polyMesh
\rm -rf VTK case.foam history
