#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

mv log.CavBubbleFoam log1.CavBubbleFoam
rm log.decomposePar
mv info.csv info1.csv
runApplication decomposePar
runParallel $application

# ----------------------------------------------------------------- end-of-file
